#! /bin/bash
wget  -O "downloaded_audiobooks/Louis Couperus_-_Eline Vere; Een Haagsche roman_::_eline_vere_cj_0810_librivox_64kb_mp3.zip" http://www.archive.org/download/eline_vere_cj_0810_librivox/eline_vere_cj_0810_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Hendrik Conscience_-_De Leeuw van Vlaenderen of de Slag der Gulden Sporen_::_leeuw_van_vlaenderen_as_librivox_64kb_mp3.zip" http://www.archive.org/download/leeuw_van_vlaenderen_as_librivox/leeuw_van_vlaenderen_as_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Johan de Meester_-_De zonde in het deftige dorp_::_zonde_deftige_dorp_0809_librivox_64kb_mp3.zip" http://www.archive.org/download/zonde_deftige_dorp_0809_librivox/zonde_deftige_dorp_0809_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Hendricus Scheepstra_-_Het boek van Ot en Sien_::_ot_en_sien_0910_librivox_64kb_mp3.zip" http://www.archive.org/download/ot_en_sien_0910_librivox/ot_en_sien_0910_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Brieven van den nutteloozen toeschouwer_::_nutteloozen_toeschouwer_0901_librivox_64kb_mp3.zip" http://www.archive.org/download/nutteloozen_toeschouwer_0901_librivox/nutteloozen_toeschouwer_0901_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/A.L.G. Bosboom-Toussaint_-_Majoor Frans_::_majoor_frans_as_64kb_mp3.zip" http://www.archive.org/download/majoor_frans_as/majoor_frans_as_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Frederik van Eeden_-_De kleine Johannes_::_kleine_johannes_0909_librivox_64kb_mp3.zip" http://www.archive.org/download/kleine_johannes_0909_librivox/kleine_johannes_0909_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Cornelis Johannes Kieviet_-_De zoon van Dik Trom_::_zoon_dik_trom_0908_librivox_64kb_mp3.zip" http://www.archive.org/download/zoon_dik_trom_0908_librivox/zoon_dik_trom_0908_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Leo Tolstoy_-_Anna Karenina (Nederlands)_::_annakarenina_dutch_1011_librivox_64kb_mp3.zip" http://www.archive.org/download/annakarenina_dutch_1011_librivox/annakarenina_dutch_1011_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louisa May Alcott_-_Onder Moeders Vleugels_::_moeders_vleugels_0711_64kb_mp3.zip" http://www.archive.org/download/moeders_vleugels_0711/moeders_vleugels_0711_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Andrew Murray_-_Nederigheid_::_nederigheid_jh_2_librivox_64kb_mp3.zip" http://www.archive.org/download/nederigheid_jh_2_librivox/nederigheid_jh_2_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Johan Been_-_Paddeltje, de scheepsjongen van Michiel de Ruijter_::_paddeltje_0811_librivox_64kb_mp3.zip" http://www.archive.org/download/paddeltje_0811_librivox/paddeltje_0811_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jules Verne_-_Naar het Middelpunt der Aarde_::_middelpunt_aarde_0906_librivox_64kb_mp3.zip" http://www.archive.org/download/middelpunt_aarde_0906_librivox/middelpunt_aarde_0906_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Selma Lagerlöf_-_Niels Holgersson's Wonderbare Reis_::_niels_holgerssons_co_librivox_64kb_mp3.zip" http://www.archive.org/download/niels_holgerssons_co_librivox/niels_holgerssons_co_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Unknown_-_De Reis om de Wereld in 80 Dagen_::_80dagen_verne_0904_librivox_64kb_mp3.zip" http://www.archive.org/download/80dagen_verne_0904_librivox/80dagen_verne_0904_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Nicolaas Beets (AKA Hildebrand)_-_Camera Obscura_::_camera_obscura_0809_librivox_64kb_mp3.zip" http://www.archive.org/download/camera_obscura_0809_librivox/camera_obscura_0809_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Unknown_-_Reinaart de Vos_::_reinaartdevos_0812_librivox_64kb_mp3.zip" http://www.archive.org/download/reinaartdevos_0812_librivox/reinaartdevos_0812_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Cornelis Johannes Kieviet_-_Uit het leven van Dik Trom_::_dik_trom_0905_librivox_64kb_mp3.zip" http://www.archive.org/download/dik_trom_0905_librivox/dik_trom_0905_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Harriet Beecher Stowe_-_De Negerhut_::_negerhut_0912_librivox_64kb_mp3.zip" http://www.archive.org/download/negerhut_0912_librivox/negerhut_0912_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jules Verne_-_20.000 Mijlen onder Zee_::_20000_mijlen_1003_librivox_64kb_mp3.zip" http://www.archive.org/download/20000_mijlen_1003_librivox/20000_mijlen_1003_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Nienke van Hichtum_-_Afke's tiental_::_afkes_tiental_1001_librivox_64kb_mp3.zip" http://www.archive.org/download/afkes_tiental_1001_librivox/afkes_tiental_1001_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/E.J. Potgieter_-_Jan, Jannetje en hun jongste kind_::_jan_jannetje_as_librivox_64kb_mp3.zip" http://www.archive.org/download/jan_jannetje_as_librivox/jan_jannetje_as_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jacob van Lennep_-_De lotgevallen van Ferdinand Huyck_::_ferdinand_huyck_as_librivox_64kb_mp3.zip" http://www.archive.org/download/ferdinand_huyck_as_librivox/ferdinand_huyck_as_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Unknown_-_Verzamelde korte Nederlandstalige Werken_::_verzameld_nederlands_001_0905_64kb_mp3.zip" http://www.archive.org/download/verzameld_nederlands_001_0905/verzameld_nederlands_001_0905_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Betje Wolff_-_Historie van mejuffrouw Sara Burgerhart_::_sara_burgerhart_cj_librivox_64kb_mp3.zip" http://www.archive.org/download/sara_burgerhart_cj_librivox/sara_burgerhart_cj_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Miguel de Cervantes Saavedra_-_Don Quichot van La Mancha_::_don_quichot_la_mancha_bt_librivox_64kb_mp3.zip" http://www.archive.org/download/don_quichot_la_mancha_bt_librivox/don_quichot_la_mancha_bt_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Multatuli_-_Max Havelaar, of de koffij-veilingen der Nederlandsche Handel-Maatschappij_::_max_havelaar_as_librivox_64kb_mp3.zip" http://www.archive.org/download/max_havelaar_as_librivox/max_havelaar_as_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Sir Arthur Conan Doyle_-_Verhalen van Sherlock Holmes_::_sherlockholmes_verhalen_1002_librivox_64kb_mp3.zip" http://www.archive.org/download/sherlockholmes_verhalen_1002_librivox/sherlockholmes_verhalen_1002_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Van Oude Menschen de Dingen, die Voorbij Gaan_::_oude_menschen_cj_64kb_mp3.zip" http://www.archive.org/download/oude_menschen_cj/oude_menschen_cj_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Marcellus Emants_-_Een nagelaten bekentenis_::_nagelaten_bekentenis_0806_librivox_64kb_mp3.zip" http://www.archive.org/download/nagelaten_bekentenis_0806_librivox/nagelaten_bekentenis_0806_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Hans Christian Andersen_-_Andersens Sproken en vertellingen_::_sproken_andersen_0906_librivox_64kb_mp3.zip" http://www.archive.org/download/sproken_andersen_0906_librivox/sproken_andersen_0906_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Frederik van Eeden_-_Van de Koele Meren des Doods_::_koele_meren_1004_librivox_64kb_mp3.zip" http://www.archive.org/download/koele_meren_1004_librivox/koele_meren_1004_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/C. Joh. Kieviet_-_Toen Dik Trom een Jongen Was_::_dik_trom_3_1012_librivox_64kb_mp3.zip" http://www.archive.org/download/dik_trom_3_1012_librivox/dik_trom_3_1012_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Kieviet, Cornelis Johannes_-_Fulco de Minstreel_::_fulco_de_minstreel_0807_librivox_64kb_mp3.zip" http://www.archive.org/download/fulco_de_minstreel_0807_librivox/fulco_de_minstreel_0807_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Cornelis Johannes Kieviet_-_Dik Trom en zijn Dorpsgenooten_::_dik_trom_4_1104_librivox_64kb_mp3.zip" http://www.archive.org/download/dik_trom_4_1104_librivox/dik_trom_4_1104_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Een Kerstlied in Proza_::_kerstlied_proza_0911_librivox_64kb_mp3.zip" http://www.archive.org/download/kerstlied_proza_0911_librivox/kerstlied_proza_0911_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jan Schenkman_-_St. Nikolaas en zijn knecht_::_sinterklaas_1010_librivox_64kb_mp3.zip" http://www.archive.org/download/sinterklaas_1010_librivox/sinterklaas_1010_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Henriette van Noorden_-_Weet je nog wel van toen?_::_weet_je_nog_as_librivox_64kb_mp3.zip" http://www.archive.org/download/weet_je_nog_as_librivox/weet_je_nog_as_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Korte Verhalen van Louis Couperus_::_korte_verhalen_couperus_1004_librivox_64kb_mp3.zip" http://www.archive.org/download/korte_verhalen_couperus_1004_librivox/korte_verhalen_couperus_1004_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Gerard Keller_-_Het testament van mevrouw De Tonnette_::_testament_tonnette_1005_librivox_64kb_mp3.zip" http://www.archive.org/download/testament_tonnette_1005_librivox/testament_tonnette_1005_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_De Behekste Man of de Gesloten Koop_::_behekste_man_1012_librivox_64kb_mp3.zip" http://www.archive.org/download/behekste_man_1012_librivox/behekste_man_1012_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Thomas a Kempis_-_De navolging van Christus_::_navolging_christus_1103_librivox_64kb_mp3.zip" http://www.archive.org/download/navolging_christus_1103_librivox/navolging_christus_1103_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Unknown_-_Familie en kennissen_::_familie_kennissen_0906_librivox_64kb_mp3.zip" http://www.archive.org/download/familie_kennissen_0906_librivox/familie_kennissen_0906_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Anoniem_-_Geschiedenis van een Neger_::_geschiedenis_neger_1105_librivox_64kb_mp3.zip" http://www.archive.org/download/geschiedenis_neger_1105_librivox/geschiedenis_neger_1105_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Willem Ysbrantsz Bontekoe_-_Journael ofte gedenckwaerdige beschrijvinghe van de Oost-Indische reyse_::_journael_bontekoe_0904_librivox_64kb_mp3.zip" http://www.archive.org/download/journael_bontekoe_0904_librivox/journael_bontekoe_0904_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Herman Heijermans jr._-_Gevleugelde Daden_::_gevleugelde_daden_1005_librivox_64kb_mp3.zip" http://www.archive.org/download/gevleugelde_daden_1005_librivox/gevleugelde_daden_1005_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jules Verne_-_Michael Strogoff, de Koerier van den Czaar_::_strogoff_verne_0911_librivox_64kb_mp3.zip" http://www.archive.org/download/strogoff_verne_0911_librivox/strogoff_verne_0911_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/A.L.G. Bosboom-Toussaint_-_De Delftsche Wonderdokter_::_wonderdokter_0912_librivox_64kb_mp3.zip" http://www.archive.org/download/wonderdokter_0912_librivox/wonderdokter_0912_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Nelly_::_nelly_1012_librivox_64kb_mp3.zip" http://www.archive.org/download/nelly_1012_librivox/nelly_1012_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Eli Heimans_-_Willem Roda_::_willem_roda_0812_librivox_64kb_mp3.zip" http://www.archive.org/download/willem_roda_0812_librivox/willem_roda_0812_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Johan Been_-_Om de schatten van Il Tigretto_::_il_tigretto_0902_librivox_64kb_mp3.zip" http://www.archive.org/download/il_tigretto_0902_librivox/il_tigretto_0902_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Daniel Defoe_-_Lotgevallen van Robinson Crusoë_::_robinson_crusoe_1103_librivox_64kb_mp3.zip" http://www.archive.org/download/robinson_crusoe_1103_librivox/robinson_crusoe_1103_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Multatuli_-_Minnebrieven_::_minnebrieven_1008_librivox_64kb_mp3.zip" http://www.archive.org/download/minnebrieven_1008_librivox/minnebrieven_1008_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Marcellus Emants_-_Zes Novellen_::_zesnovellen_emants_0911_librivox_64kb_mp3.zip" http://www.archive.org/download/zesnovellen_emants_0911_librivox/zesnovellen_emants_0911_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Sir Arthur Conan Doyle_-_De Agra-Schat_::_agra-schat_1012_librivox_64kb_mp3.zip" http://www.archive.org/download/agra-schat_1012_librivox/agra-schat_1012_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/anoniem_-_Aljaska en de Canada-spoorweg_::_aljaska_canada-spoorweg_1105_librivox_64kb_mp3.zip" http://www.archive.org/download/aljaska_canada-spoorweg_1105_librivox/aljaska_canada-spoorweg_1105_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jan Bruylants_-_Tijl Uilenspiegel in Vlaanderen_::_tijl_uilenspiegel_1011_librivox_64kb_mp3.zip" http://www.archive.org/download/tijl_uilenspiegel_1011_librivox/tijl_uilenspiegel_1011_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Darwin_-_Het Ontstaan der Soorten_::_ontstaan_soorten_darwin_1107_lv_64kb_mp3.zip" http://www.archive.org/download/ontstaan_soorten_darwin_1107_lv/ontstaan_soorten_darwin_1107_lv_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Alphonse Olterdissen_-_Drei korte verhaole in ‘t Mestreechs_::_olterdissen_64kb_mp3.zip" http://www.archive.org/download/olterdissen/olterdissen_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Mr. Hieronymus van Alphen_-_Kleine Gedigten voor Kinderen_::_kleine_gedigten_voor_kinderen_1001_librivox_64kb_mp3.zip" http://www.archive.org/download/kleine_gedigten_voor_kinderen_1001_librivox/kleine_gedigten_voor_kinderen_1001_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Unknown_-_Gediechte in ut Mestreechs_::_gediechte_mestreechs_0909_librivox_64kb_mp3.zip" http://www.archive.org/download/gediechte_mestreechs_0909_librivox/gediechte_mestreechs_0909_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/P. Visser_-_De Vliegende Hollander_::_vliegende_hollander_1101_librivox_64kb_mp3.zip" http://www.archive.org/download/vliegende_hollander_1101_librivox/vliegende_hollander_1101_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Olivier Twist_::_olivier_twist_1106_librivox_64kb_mp3.zip" http://www.archive.org/download/olivier_twist_1106_librivox/olivier_twist_1106_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Mark Twain_-_De Lotgevallen van Tom Sawyer_::_lotgevallen_tom_sawyer_1004_librivox_64kb_mp3.zip" http://www.archive.org/download/lotgevallen_tom_sawyer_1004_librivox/lotgevallen_tom_sawyer_1004_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/George Lodewijk Kepper_-_Een ongeluksvogel_::_ongeluksvogel_1107_librivox_64kb_mp3.zip" http://www.archive.org/download/ongeluksvogel_1107_librivox/ongeluksvogel_1107_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Schetsen uit Amerika_::_schetsen_amerika_1007_librivox_64kb_mp3.zip" http://www.archive.org/download/schetsen_amerika_1007_librivox/schetsen_amerika_1007_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_De Gevaren van Sommige Engelse Gevangenen_::_gevaren_engelse_gevangenen_1102_librivox_64kb_mp3.zip" http://www.archive.org/download/gevaren_engelse_gevangenen_1102_librivox/gevaren_engelse_gevangenen_1102_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Helena_::_helena_1209_1209_64kb_mp3.zip" http://www.archive.org/download/helena_1209_1209/helena_1209_1209_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Mopes de Kluizenaar_::_mopes_1102_librivox_64kb_mp3.zip" http://www.archive.org/download/mopes_1102_librivox/mopes_1102_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Het Geheim van Edwin Drood_::_edwin_drood_1206_librivox_64kb_mp3.zip" http://www.archive.org/download/edwin_drood_1206_librivox/edwin_drood_1206_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jack London_-_Als de Natuur Roept_::_als_de_natuur_roept_1112_librivox_64kb_mp3.zip" http://www.archive.org/download/als_de_natuur_roept_1112_librivox/als_de_natuur_roept_1112_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_De Krekel achter de Haardplaat_::_de_krekel_achter_de_haardplaat_1011_librivox_64kb_mp3.zip" http://www.archive.org/download/de_krekel_achter_de_haardplaat_1011_librivox/de_krekel_achter_de_haardplaat_1011_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Sir Walter Scott_-_Ivanhoe (NL)_::_ivanhoe_nl_1206_librivox_64kb_mp3.zip" http://www.archive.org/download/ivanhoe_nl_1206_librivox/ivanhoe_nl_1206_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/De Schoolmeester_-_Natuurlijke Historie voor de Jeugd_::_natuurlijke_historie_1010_librivox_64kb_mp3.zip" http://www.archive.org/download/natuurlijke_historie_1010_librivox/natuurlijke_historie_1010_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_De Kerkklokken_::_kerkklokken_1012_librivox_64kb_mp3.zip" http://www.archive.org/download/kerkklokken_1012_librivox/kerkklokken_1012_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Geen Uitweg_::_geen_uitweg_1102_librivox_64kb_mp3.zip" http://www.archive.org/download/geen_uitweg_1102_librivox/geen_uitweg_1102_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_In Londen en Parijs_::_in_londen_en_parijs_1108_librivox_64kb_mp3.zip" http://www.archive.org/download/in_londen_en_parijs_1108_librivox/in_londen_en_parijs_1108_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jonathan Swift_-_Gulliver’s Reizen_::_gullivers_reizen_1111_librivox_64kb_mp3.zip" http://www.archive.org/download/gullivers_reizen_1111_librivox/gullivers_reizen_1111_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Juffrouw Lirriper's Legaat_::_lirriper_legaat_1101_librivox_64kb_mp3.zip" http://www.archive.org/download/lirriper_legaat_1101_librivox/lirriper_legaat_1101_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Overdrukken_::_overdrukken_1104_librivox_64kb_mp3.zip" http://www.archive.org/download/overdrukken_1104_librivox/overdrukken_1104_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Juffrouw Lirriper en haar Commensalen_::_juffrouw_lirriper_commensalen_mc_librivox_64kb_mp3.zip" http://www.archive.org/download/juffrouw_lirriper_commensalen_mc_librivox/juffrouw_lirriper_commensalen_mc_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Tafereelen uit Italie_::_tafereelen_italie_1005_librivox_64kb_mp3.zip" http://www.archive.org/download/tafereelen_italie_1005_librivox/tafereelen_italie_1005_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Een Huis te Huur_::_huis_te_huur_1101_librivox_64kb_mp3.zip" http://www.archive.org/download/huis_te_huur_1101_librivox/huis_te_huur_1101_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jane Austen_-_Gevoel en Verstand_::_gevoel_verstand_1108_librivox_64kb_mp3.zip" http://www.archive.org/download/gevoel_verstand_1108_librivox/gevoel_verstand_1108_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_De Strijd des Levens_::_strijd_des_levens_1012_librivox_64kb_mp3.zip" http://www.archive.org/download/strijd_des_levens_1012_librivox/strijd_des_levens_1012_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_David Copperfield (NL)_::_david_copperfield_nl_1204_librivox_64kb_mp3.zip" http://www.archive.org/download/david_copperfield_nl_1204_librivox/david_copperfield_nl_1204_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Frederik van Eeden_-_Pauls Ontwaken_::_pauls_ontwaken_1108_librivox_64kb_mp3.zip" http://www.archive.org/download/pauls_ontwaken_1108_librivox/pauls_ontwaken_1108_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Paulina Jacoba Cohen-de Vries_-_Kinderen uit m'n Klas_::_kinderen_klas_1201_librivox_64kb_mp3.zip" http://www.archive.org/download/kinderen_klas_1201_librivox/kinderen_klas_1201_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/J. J. A. Goeverneur_-_Oude Sprookjes_::_oude_sprookjes_goeverneur_1108_librivox_64kb_mp3.zip" http://www.archive.org/download/oude_sprookjes_goeverneur_1108_librivox/oude_sprookjes_goeverneur_1108_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Unknown_-_Twee Redevoeringen tegen de Slavernij in de Nederlandse Koloniën_::_redevoeringen_slavernij_1104_librivox_64kb_mp3.zip" http://www.archive.org/download/redevoeringen_slavernij_1104_librivox/redevoeringen_slavernij_1104_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jack London_-_Vóór Adam's Tijd_::_voor_adam_1202_librivox_64kb_mp3.zip" http://www.archive.org/download/voor_adam_1202_librivox/voor_adam_1202_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Alexandre Dumas_-_De Drie Musketiers_::_drie_musketiers_1111_librivox_64kb_mp3.zip" http://www.archive.org/download/drie_musketiers_1111_librivox/drie_musketiers_1111_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Drie Korte Verhalen van Charles Dickens_::_Drie_korte_verhalen_dickens_1106_librivox_64kb_mp3.zip" http://www.archive.org/download/Drie_korte_verhalen_dickens_1106_librivox/Drie_korte_verhalen_dickens_1106_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jack London_-_Pit-tah, de Grijze Wolf_::_pit-tah_1202_librivox_64kb_mp3.zip" http://www.archive.org/download/pit-tah_1202_librivox/pit-tah_1202_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Dickens, Charles_-_Nikolaas Nickleby_::_nikolaas_nickleby_1202_64kb_mp3.zip" http://www.archive.org/download/nikolaas_nickleby_1202/nikolaas_nickleby_1202_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jacob Israël de Haan_-_Pijpelijntjes_::_pijpelijntjes_1103_librivox_64kb_mp3.zip" http://www.archive.org/download/pijpelijntjes_1103_librivox/pijpelijntjes_1103_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Justus van Maurik_-_Krates Een Levensbeeld_::_krates_1502_librivox_64kb_mp3.zip" http://www.archive.org/download//krates_1502_librivox/krates_1502_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Julius Dub_-_Beknopte uiteenzetting van de theorie van Darwin over het ontstaan der plant- en diervormen_::_beknopt_darwin_1204_librivox_64kb_mp3.zip" http://www.archive.org/download/beknopt_darwin_1204_librivox/beknopt_darwin_1204_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Adriaan Loosjes Pzn._-_Leven van Maurits Lijnslager deel 4_::_het_leven_van_maurits_lijnslager_deel_4_1605_librivox_64kb_mp3.zip" https://www.archive.org/download//het_leven_van_maurits_lijnslager_deel_4_1605_librivox/het_leven_van_maurits_lijnslager_deel_4_1605_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louise Zaalberg_-_Strijd om de Schatten van Alva of de Watergeuzen in 1572_::_een_strijd_om_de_schatten_van_alva_1411_librivox_64kb_mp3.zip" http://www.archive.org/download//een_strijd_om_de_schatten_van_alva_1411_librivox/een_strijd_om_de_schatten_van_alva_1411_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ A.C. Kuiper_-_Elsje_::_elsje_1310_librivox_64kb_mp3.zip" http://www.archive.org/download//elsje_1310_librivox/elsje_1310_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Victor Hugo_-_Ellendigen - Deel 1 - Fantine_::_ellendigen_deel_1_fantine_1404_librivox_64kb_mp3.zip" http://www.archive.org/download//ellendigen_deel_1_fantine_1404_librivox/ellendigen_deel_1_fantine_1404_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Adriaan Loosjes Pzn._-_Leven van Maurits Lijnslager deel 2_::_het_leven_van_maurits_lijnslager_deel_2_1603_librivox_64kb_mp3.zip" https://www.archive.org/download//het_leven_van_maurits_lijnslager_deel_2_1603_librivox/het_leven_van_maurits_lijnslager_deel_2_1603_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Adriaan Loosjes Pzn._-_Leven van Hillegonda Buisman - deel 2_::_het_leven_van_hillegonda_buisman_-_deel_2_1609_librivox_64kb_mp3.zip" https://www.archive.org/download//het_leven_van_hillegonda_buisman_-_deel_2_1609_librivox/het_leven_van_hillegonda_buisman_-_deel_2_1609_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Adriaan Loosjes Pzn._-_Leven van Maurits Lijnslager deel 3_::_maurits_lijnslager_3_1604_librivox_64kb_mp3.zip" https://www.archive.org/download//maurits_lijnslager_3_1604_librivox/maurits_lijnslager_3_1604_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Melis Stoke_-_Van Aardappel-mes tot Officiersdegen_::_aardappelmes_1301_librivox_64kb_mp3.zip" http://www.archive.org/download/aardappelmes_1301_librivox/aardappelmes_1301_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Henri Emile Koopmans van Boekeren_-_Jeanne D'Arc, de Maagd van Orléans_::_jeanne_darc_1306_librivox_64kb_mp3.zip" http://www.archive.org/download/jeanne_darc_1306_librivox/jeanne_darc_1306_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jules Verne_-_Kinderen van Kapitein Grant_::_de_kinderen_van_kapitein_grant_2201_librivox_64kb_mp3.zip" https://www.archive.org/download/de_kinderen_van_kapitein_grant_2201_librivox/de_kinderen_van_kapitein_grant_2201_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Adriaan Loosjes Pzn._-_Leven van Hillegonda Buisman - deel 1_::_het_leven_van_hillegonda_buisman_-_deel_1_1606_librivox_64kb_mp3.zip" https://www.archive.org/download//het_leven_van_hillegonda_buisman_-_deel_1_1606_librivox/het_leven_van_hillegonda_buisman_-_deel_1_1606_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Jacob van Lennep_-_Klaasje Zevenster, deel 1_::_klaasje_zevenster_deel_1_1509_librivox_64kb_mp3.zip" http://www.archive.org/download//klaasje_zevenster_deel_1_1509_librivox/klaasje_zevenster_deel_1_1509_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jean Webster_-_Vadertje Langbeen_::_vadertje_langbeen_1608_librivox_64kb_mp3.zip" https://www.archive.org/download//vadertje_langbeen_1608_librivox/vadertje_langbeen_1608_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_De kleine zielen_::_kleinezielen_1003_librivox_64kb_mp3.zip" http://www.archive.org/download/kleinezielen_1003_librivox/kleinezielen_1003_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_De Gedenkschriften van Jozef Grimaldi de Clown_::_grimaldi_1111_librivox_64kb_mp3.zip" http://www.archive.org/download/grimaldi_1111_librivox/grimaldi_1111_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/William Makepeace Thackeray_-_De Kermis der IJdelheid_::_kermis_ijdelheid_1111_librivox_64kb_mp3.zip" http://www.archive.org/download/kermis_ijdelheid_1111_librivox/kermis_ijdelheid_1111_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Slechte Tijden_::_slechte_tijden_1110_librivox_64kb_mp3.zip" http://www.archive.org/download/slechte_tijden_1110_librivox/slechte_tijden_1110_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Noodlot_::_noodlot_1310_librivox_64kb_mp3.zip" http://www.archive.org/download//noodlot_1310_librivox/noodlot_1310_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Guido Gezelle_-_Vlaemsche Dichtoefeningen_::_vlaemsche_dichtoefeningen_1202_librivox_64kb_mp3.zip" http://www.archive.org/download/vlaemsche_dichtoefeningen_1202_librivox/vlaemsche_dichtoefeningen_1202_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Kleine Dorrit_::_kleinedorrit_1004_librivox_64kb_mp3.zip" http://www.archive.org/download/kleinedorrit_1004_librivox/kleinedorrit_1004_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Zwevende Schaakbord_::_zwevende_schaakbord_1304_librivox_64kb_mp3.zip" http://www.archive.org/download/zwevende_schaakbord_1304_librivox/zwevende_schaakbord_1304_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_De Pickwick-Club_::_pickwick-club_1208_librivox_64kb_mp3.zip" http://www.archive.org/download/pickwick-club_1208_librivox/pickwick-club_1208_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Karl May_-_Schat in het Zilvermeer_::_schat_zilvermeer_1212_librivox_64kb_mp3.zip" http://www.archive.org/download/schat_zilvermeer_1212_librivox/schat_zilvermeer_1212_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Hector Malot_-_Alleen op de wereld_::_alleen_wereld_1002_librivox_64kb_mp3.zip" http://www.archive.org/download/alleen_wereld_1002_librivox/alleen_wereld_1002_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Various_-_Verzamelde korte Nederlandstalige Werken 003_::_verzameld_nederlands_003_1210_lv_64kb_mp3.zip" http://www.archive.org/download/verzameld_nederlands_003_1210_lv/verzameld_nederlands_003_1210_lv_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Carry van Bruggen_-_Coquette Vrouw_::_een_coquette_vrouw_2102_librivox_64kb_mp3.zip" https://www.archive.org/download//een_coquette_vrouw_2102_librivox/een_coquette_vrouw_2102_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Jacob van Lennep_-_Roos van Dekama_::_de_roos_van_dekama_1507_librivox_64kb_mp3.zip" http://www.archive.org/download//de_roos_van_dekama_1507_librivox/de_roos_van_dekama_1507_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Pieter Louwerse_-_Alles Zingt_::_alles_zingt_1810_librivox_64kb_mp3.zip" https://www.archive.org/download//alles_zingt_1810_librivox/alles_zingt_1810_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Multatuli_-_Geschiedenis van Woutertje Pieterse_::_woutertje_pieterse_1310_librivox_64kb_mp3.zip" http://www.archive.org/download//woutertje_pieterse_1310_librivox/woutertje_pieterse_1310_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Maarten Chuzzlewit_::_maarten_chuzzlewit_1206_librivox_64kb_mp3.zip" http://www.archive.org/download/maarten_chuzzlewit_1206_librivox/maarten_chuzzlewit_1206_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Late Leven_::_lateleven_1301_librivox_64kb_mp3.zip" http://www.archive.org/download/lateleven_1301_librivox/lateleven_1301_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Jacob van Lennep_-_Klaasje Zevenster, deel 3_::_klaasje_zevenster_deel_3_1903_librivox_64kb_mp3.zip" https://www.archive.org/download//klaasje_zevenster_deel_3_1903_librivox/klaasje_zevenster_deel_3_1903_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Psyche_::_psyche_1312_librivox_64kb_mp3.zip" http://www.archive.org/download//psyche_1312_librivox/psyche_1312_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Herman Heijermans, Jr._-_Falklandjes_::_falklandjes_1211_librivox_64kb_mp3.zip" http://www.archive.org/download/falklandjes_1211_librivox/falklandjes_1211_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Paul Adriaan Daum_-_Aboe Bakar_::_aboe_bakar_1805_librivox_64kb_mp3.zip" https://www.archive.org/download//aboe_bakar_1805_librivox/aboe_bakar_1805_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Paul Adriaan Daum_-_Van der Linden's c.s._::_de_van_der_lindens_cs_1811_librivox_64kb_mp3.zip" https://www.archive.org/download//de_van_der_lindens_cs_1811_librivox/de_van_der_lindens_cs_1811_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Statenvertaling_-_Bible (Bijbel SV) NT 04: het Evangelie van Johannes_::_biblesvnt04hetevangelievanjohannes_1704_librivox_64kb_mp3.zip" https://www.archive.org/download//biblesvnt04hetevangelievanjohannes_1704_librivox/biblesvnt04hetevangelievanjohannes_1704_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Adriaan Loosjes Pzn._-_Leven van Hillegonda Buisman - deel 4_::_hillegonda_buisman_deel_4_1612_librivox_64kb_mp3.zip" https://www.archive.org/download//hillegonda_buisman_deel_4_1612_librivox/hillegonda_buisman_deel_4_1612_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Extaze, een boek van geluk_::_extaze_een_boek_van_geluk_1310_librivox_64kb_mp3.zip" http://www.archive.org/download//extaze_een_boek_van_geluk_1310_librivox/extaze_een_boek_van_geluk_1310_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Augusta de Wit_-_Orpheus in de dessa_::_orpheus_in_de_dessa_1812_librivox_64kb_mp3.zip" https://www.archive.org/download//orpheus_in_de_dessa_1812_librivox/orpheus_in_de_dessa_1812_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Dombey en Zoon_::_dombey_en_zoon_1301_librivox_64kb_mp3.zip" http://www.archive.org/download/dombey_en_zoon_1301_librivox/dombey_en_zoon_1301_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Cissy van Marxveldt_-_H.B.S. tijd van Joop ter Heul_::_hbs_tijd_van_joop_ter_heul_1904_librivox_64kb_mp3.zip" https://www.archive.org/download//hbs_tijd_van_joop_ter_heul_1904_librivox/hbs_tijd_van_joop_ter_heul_1904_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Lent van vaerzen_::_lentvaerzen_1301_librivox_64kb_mp3.zip" http://www.archive.org/download/lentvaerzen_1301_librivox/lentvaerzen_1301_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Paul Adriaan Daum_-_Hoe hij raad van Indië werd_::_hoe_hij_raad_van_indie_werd_1810_librivox_64kb_mp3.zip" https://www.archive.org/download//hoe_hij_raad_van_indie_werd_1810_librivox/hoe_hij_raad_van_indie_werd_1810_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Klok van Meester Humphrey_::_klok_van_meester_humphrey_1210_librivox_64kb_mp3.zip" http://www.archive.org/download/klok_van_meester_humphrey_1210_librivox/klok_van_meester_humphrey_1210_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jacob Winkler Prins_-_Sonnetten_::_sonnetten_prins_1807_librivox_64kb_mp3.zip" https://www.archive.org/download//sonnetten_prins_1807_librivox/sonnetten_prins_1807_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Statenvertaling_-_Bible (Bijbel SV) NT 27: de Openbaring van Johannes_::_biblebijbelopenbaring_1711_librivox_64kb_mp3.zip" https://www.archive.org/download//biblebijbelopenbaring_1711_librivox/biblebijbelopenbaring_1711_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jacob Cats_-_Hofgedachten_::_hofgedachten_1705_librivox_64kb_mp3.zip" https://www.archive.org/download//hofgedachten_1705_librivox/hofgedachten_1705_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jacobus Craandijk_-_Twenthe_::_twenthe_1211_librivox_64kb_mp3.zip" http://www.archive.org/download/twenthe_1211_librivox/twenthe_1211_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Adriaan Loosjes Pzn._-_leven van Johannes Wouter Blommesteyn - deel 3_::_johannes_blommesteyn_3_1709_librivox_64kb_mp3.zip" https://www.archive.org/download//johannes_blommesteyn_3_1709_librivox/johannes_blommesteyn_3_1709_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Een reiziger, die geen handel drijft_::_reizigerdiegeenhandeldrijft_1302_librivox_64kb_mp3.zip" http://www.archive.org/download/reizigerdiegeenhandeldrijft_1302_librivox/reizigerdiegeenhandeldrijft_1302_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Langs Lijnen van Geleidelijkheid_::_langs_lijnen_van_geleidelijkheid_1312_librivox_64kb_mp3.zip" http://www.archive.org/download//langs_lijnen_van_geleidelijkheid_1312_librivox/langs_lijnen_van_geleidelijkheid_1312_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Fred. Berens_-_Uit de schooljaren van Hans Doncker_::_uit_de_schooljaren_van_hans_doncker_2202_librivox_64kb_mp3.zip" https://www.archive.org/download/uit_de_schooljaren_van_hans_doncker_2202_librivox/uit_de_schooljaren_van_hans_doncker_2202_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Adriaan Loosjes Pzn._-_leven van Johannes Wouter Blommesteyn - deel 2_::_johannes_blommesteyn_2_1706_librivox_64kb_mp3.zip" https://www.archive.org/download//johannes_blommesteyn_2_1706_librivox/johannes_blommesteyn_2_1706_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Adriaan Loosjes Pzn._-_Leven van Hillegonda Buisman - deel 3_::_hillegonda_buisman_deel_3_1611_librivox_64kb_mp3.zip" https://www.archive.org/download//hillegonda_buisman_deel_3_1611_librivox/hillegonda_buisman_deel_3_1611_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/A. L. G. Bosboom-Toussaint_-_Langs een omweg_::_langs_omweg_1508_librivox_64kb_mp3.zip" http://www.archive.org/download//langs_omweg_1508_librivox/langs_omweg_1508_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jacobus Craandijk_-_Op Walcheren_::_op_walcheren_1211_librivox_64kb_mp3.zip" http://www.archive.org/download/op_walcheren_1211_librivox/op_walcheren_1211_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Adriaan Loosjes Pzn._-_Leven van Maurits Lijnslager deel 1_::_het_leven_van_maurits_lijnslager_deel_1_1602_librivox_64kb_mp3.zip" http://www.archive.org/download//het_leven_van_maurits_lijnslager_deel_1_1602_librivox/het_leven_van_maurits_lijnslager_deel_1_1602_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Adriaan Loosjes Pzn._-_leven van Johannes Wouter Blommesteyn - deel 4_::_johannes_blommesteyn_4_1712_librivox_64kb_mp3.zip" https://www.archive.org/download//johannes_blommesteyn_4_1712_librivox/johannes_blommesteyn_4_1712_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Anonymous_-_Duizend en één Nacht, Derde deel_::_duizend_en_een_nacht_3_1410_librivox_64kb_mp3.zip" http://www.archive.org/download//duizend_en_een_nacht_3_1410_librivox/duizend_en_een_nacht_3_1410_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Adriaan Loosjes Pzn._-_leven van Johannes Wouter Blommesteyn - deel 1_::_johannes_blommesteyn_1_1703_librivox_64kb_mp3.zip" https://www.archive.org/download//johannes_blommesteyn_1_1703_librivox/johannes_blommesteyn_1_1703_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Jacob van Lennep_-_Pleegzoon_::_de_pleegzoon_1601_librivox_64kb_mp3.zip" http://www.archive.org/download//de_pleegzoon_1601_librivox/de_pleegzoon_1601_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Over lichtende drempels_::_over_lichtende_drempels_1403_librivox_64kb_mp3.zip" http://www.archive.org/download//over_lichtende_drempels_1403_librivox/over_lichtende_drempels_1403_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Theo Thijssen_-_Kees de Jongen_::_kees_de_jongen_1506_librivox_64kb_mp3.zip" http://www.archive.org/download//kees_de_jongen_1506_librivox/kees_de_jongen_1506_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Justus van Maurik_-_Korte Werken van Justus van Maurik_::_korte_werken_van_justus_van_maurik_1406_librivox_64kb_mp3.zip" http://www.archive.org/download//korte_werken_van_justus_van_maurik_1406_librivox/korte_werken_van_justus_van_maurik_1406_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Victor Hugo_-_Ellendigen - Deel 4 - St. Denis_::_de_ellendigen_deel_4_st_denis_1408_librivox_64kb_mp3.zip" http://www.archive.org/download//de_ellendigen_deel_4_st_denis_1408_librivox/de_ellendigen_deel_4_st_denis_1408_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Betje Wolff_-_Proeve over de opvoeding, aan de Nederlandsche moeders_::_proeve_over_de_opvoeding_aan_de_nederlandsche_moeders_1_librivox_64kb_mp3.zip" http://www.archive.org/download//proeve_over_de_opvoeding_aan_de_nederlandsche_moeders_1_librivox/proeve_over_de_opvoeding_aan_de_nederlandsche_moeders_1_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Heilige Weten_::_heilige_weten_1305_64kb_mp3.zip" http://www.archive.org/download/heilige_weten_1305/heilige_weten_1305_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Anonymous_-_Ali Baba en de veertig roovers_::_ali_baba_en_de_veertig_roovers_1411_librivox_64kb_mp3.zip" http://www.archive.org/download//ali_baba_en_de_veertig_roovers_1411_librivox/ali_baba_en_de_veertig_roovers_1411_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Pieter Louwerse_-_Schippersjongen_::_de_schippersjongen_1412_librivox_64kb_mp3.zip" http://www.archive.org/download//de_schippersjongen_1412_librivox/de_schippersjongen_1412_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Verlaten Huis_::_verlaten_huis_1306_librivox_64kb_mp3.zip" http://www.archive.org/download/verlaten_huis_1306_librivox/verlaten_huis_1306_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Jacob van Lennep_-_Elizabeth Musch_::_elizabeth_musch_1512_librivox_64kb_mp3.zip" http://www.archive.org/download//elizabeth_musch_1512_librivox/elizabeth_musch_1512_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Legende, mythe en fantazie_::_legende_mythe_en_fantazie_1403_librivox_64kb_mp3.zip" http://www.archive.org/download//legende_mythe_en_fantazie_1403_librivox/legende_mythe_en_fantazie_1403_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Anonymous_-_Duizend en één Nacht, Tweede deel_::_duizend_en_een_nacht_tweede_deel_1410_librivox_64kb_mp3.zip" http://www.archive.org/download//duizend_en_een_nacht_tweede_deel_1410_librivox/duizend_en_een_nacht_tweede_deel_1410_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Majesteit_::_majesteit_1302_librivox_64kb_mp3.zip" http://www.archive.org/download/majesteit_1302_librivox/majesteit_1302_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Pieter Louwerse_-_Willem Tell_::_willem_tell_1411_librivox_64kb_mp3.zip" http://www.archive.org/download//willem_tell_1411_librivox/willem_tell_1411_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Herakles_::_herakles_1402_librivox_64kb_mp3.zip" http://www.archive.org/download//herakles_1402_librivox/herakles_1402_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Onze Wederzijdsche Vriend_::_onze_wederzijdsche_vriend_1304_librivox_64kb_mp3.zip" http://www.archive.org/download/onze_wederzijdsche_vriend_1304_librivox/onze_wederzijdsche_vriend_1304_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Metamorfoze_::_metamorfoze_1402_librivox_64kb_mp3.zip" http://www.archive.org/download//metamorfoze_1402_librivox/metamorfoze_1402_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Paul Adriaan Daum_-_Goena - goena_::_goena_goena_1503_librivox_64kb_mp3.zip" http://www.archive.org/download//goena_goena_1503_librivox/goena_goena_1503_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Anonymous_-_Duizend en één Nacht, Vierde deel_::_duizend_en_een_nacht_4_1411_librivox_64kb_mp3.zip" http://www.archive.org/download//duizend_en_een_nacht_4_1411_librivox/duizend_en_een_nacht_4_1411_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Anonymous_-_Aladdin en de wonderlamp_::_aladdin_en_de_wonderlamp_1411_librivox_64kb_mp3.zip" http://www.archive.org/download//aladdin_en_de_wonderlamp_1411_librivox/aladdin_en_de_wonderlamp_1411_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Zielenschemering_::_zielenschemering_1302_librivox_64kb_mp3.zip" http://www.archive.org/download/zielenschemering_1302_librivox/zielenschemering_1302_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Niccolò Machiavelli_-_Vorst_::_de_vorst_1504_librivox_64kb_mp3.zip" http://www.archive.org/download//de_vorst_1504_librivox/de_vorst_1504_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jacobus Craandijk_-_In de Graafschap_::_in_de_graafschap_1402_librivox_64kb_mp3.zip" http://www.archive.org/download//in_de_graafschap_1402_librivox/in_de_graafschap_1402_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jacobus Craandijk_-_Langs de Vecht_::_langs_de_vecht_1402_librivox_64kb_mp3.zip" http://www.archive.org/download//langs_de_vecht_1402_librivox/langs_de_vecht_1402_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Fidessa_::_fidessa_1401_librivox_64kb_mp3.zip" http://www.archive.org/download//fidessa_1401_librivox/fidessa_1401_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Anonymous_-_Duizend en één Nacht, Eerste deel_::_duizend_en_een_nacht_-_deel_een_1408_librivox_64kb_mp3.zip" http://www.archive.org/download//duizend_en_een_nacht_-_deel_een_1408_librivox/duizend_en_een_nacht_-_deel_een_1408_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Pieter Harting_-_Anno 2070: een blik in de toekomst_::_anno_2070_een_blik_in_de_toekomst_1407_librivox_64kb_mp3.zip" http://www.archive.org/download//anno_2070_een_blik_in_de_toekomst_1407_librivox/anno_2070_een_blik_in_de_toekomst_1407_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Aan den Weg der Vreugde_::_weg_der_vreugde_1301_librivox_64kb_mp3.zip" http://www.archive.org/download/weg_der_vreugde_1301_librivox/weg_der_vreugde_1301_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Victor Hugo_-_Ellendigen - Deel 5 - Jean Valjean_::_de_ellendigen_deel_5_jean_valjean_1409_librivox_64kb_mp3.zip" http://www.archive.org/download//de_ellendigen_deel_5_jean_valjean_1409_librivox/de_ellendigen_deel_5_jean_valjean_1409_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Babel_::_babel_1403_librivox_64kb_mp3.zip" http://www.archive.org/download//babel_1403_librivox/babel_1403_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jacobus Craandijk_-_Mettray - Bathmen_::_mettray_bathmen_1212_librivox_64kb_mp3.zip" http://www.archive.org/download/mettray_bathmen_1212_librivox/mettray_bathmen_1212_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Groote Verwachtingen_::_grooteverwachtingen_1309_librivox_64kb_mp3.zip" http://www.archive.org/download//grooteverwachtingen_1309_librivox/grooteverwachtingen_1309_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Wereldvrede_::_wereldvrede_1303_librivox_64kb_mp3.zip" http://www.archive.org/download/wereldvrede_1303_librivox/wereldvrede_1303_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Jules Verne_-_Reis naar de Maan in 28 Dagen en 12 Uren_::_de_reis_naar_de_maan_1511_librivox_64kb_mp3.zip" http://www.archive.org/download//de_reis_naar_de_maan_1511_librivox/de_reis_naar_de_maan_1511_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Hooge Troeven_::_hooge_troeven_1303_librivox_64kb_mp3.zip" http://www.archive.org/download/hooge_troeven_1303/hooge_troeven_1303_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/ Jacob van Lennep_-_Klaasje Zevenster, deel 2_::_klaasje_zevenster_deel_2_1511_librivox_64kb_mp3.zip" http://www.archive.org/download//klaasje_zevenster_deel_2_1511_librivox/klaasje_zevenster_deel_2_1511_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Nathaniel Hawthorne_-_scharlaken letter_::_de_scharlaken_letter_1405_librivox_64kb_mp3.zip" http://www.archive.org/download//de_scharlaken_letter_1405_librivox/de_scharlaken_letter_1405_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Victor Hugo_-_Ellendigen - Deel 3 - Marius_::_de_ellendigen_-_deel_3_-_marius_1407_librivox_64kb_mp3.zip" http://www.archive.org/download//de_ellendigen_-_deel_3_-_marius_1407_librivox/de_ellendigen_-_deel_3_-_marius_1407_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Louis Couperus_-_Stille Kracht_::_stillekracht_1302_64kb_mp3.zip" http://www.archive.org/download/stillekracht_1302/stillekracht_1302_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Charles Dickens_-_Schetsen van Boz_::_schetsen_van_boz_1308_librivox_64kb_mp3.zip" http://archive.org/download/schetsen_van_boz_1308_librivox/schetsen_van_boz_1308_librivox_64kb_mp3.zip
wget  -O "downloaded_audiobooks/Victor Hugo_-_Ellendigen - Deel 2 - Cosette_::_ellendigen_-_deel_2_-_cosette_1406_librivox_64kb_mp3.zip" http://www.archive.org/download//ellendigen_-_deel_2_-_cosette_1406_librivox/ellendigen_-_deel_2_-_cosette_1406_librivox_64kb_mp3.zip
